FROM python:3.11-slim

WORKDIR /app

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код
COPY backend.py ./

EXPOSE 8001

CMD ["uvicorn", "backend:app", "--host", "0.0.0.0", "--port", "8001"]
