FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ENV VITE_API_URL=http://localhost:8001/api/generate
CMD ["npm", "run", "dev"]


# Production build stage
FROM node:20-alpine AS prodbuilder

WORKDIR /app

COPY package*.json ./
RUN npm ci --frozen-lockfile 2>/dev/null || npm install

COPY . .

ENV VITE_API_URL=http://localhost:8001/api/generate
RUN npm run build


# Nginx stage (для production)
FROM nginx:alpine

COPY --from=prodbuilder /app/dist/ /usr/share/nginx/html/
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
